services:
  - type: web
    name: berlin-okey
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: BOT_USERNAME
        value: Berlinokeybot
      - key: WEBAPP_URL
        value: "https://berlin-okey.onrender.com"
      - key: ENABLE_TELEGRAM_BOT
        value: "true"
      - key: BOT_TOKEN
        sync: false
      - key: MAX_PLAYERS
        value: "100"
      - key: MAX_ROOMS
        value: "40"
